# Master
FROM python:2-slim
LABEL maintainer="foxty@163.com"
ENV APP_BASE=/opt/node-monitor
ENV MASTER_HOST=''
WORKDIR /opt/node-monitor

COPY requirements.txt ./
COPY conf ./conf
COPY nodemonitor ./nodemonitor
COPY web/dist  ./web/dist

RUN pip install -r requirements.txt
RUN chmod +x ./nodemonitor/master_cli.py

EXPOSE 30078
EXPOSE 30079
ENTRYPOINT ["python", "./nodemonitor/master_cli.py", "-r"]
CMD ["all"]