# UI base on grafana
FROM grafana/grafana:5.2.4
LABEL maintainer="foxty@163.com"

COPY conf/grafana/provisioning /etc/grafana/provisioning
COPY conf/grafana/custom.ini /etc/grafana/custom.ini

EXPOSE 30080
ENTRYPOINT [ "/run.sh", "--config", "/etc/grafana/custom.ini" ]