{
 "title": "Nodes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "rawSql": "SELECT $__time(create_at), count(aid) FROM agent group by create_at\n"
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "rawSql": "SELECT $__time(last_report_at), count(id) FROM service group by last_report_at\n"
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "rawSql": "SELECT $__time(last_report_at), count(id) FROM service group by last_report_at\n"
    }
   ]
  },
  {
   "title": "Node List",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "rawSql": "SELECT aid, name, host, last_cpu_util, last_mem_util, last_sys_load1, last_sys_cs, status, last_msg_at from agent order by last_msg_at desc"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Load 1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "null",
     "metric": "node.system.load1",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n",
     "tags": { "aid": "*" }
    }
   ]
  },
  {
   "title": "Load 5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "null",
     "metric": "node.system.load5",
     "tags": { "aid": "*" }
    }
   ]
  },
  {
   "title": "Context Switch",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "sum",
     "downsampleFillPolicy": "null",
     "metric": "node.system.sys_cs",
     "tags": { "aid": "*" }
    }
   ]
  },
  {
   "title": "System Interrupt",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "sum",
     "downsampleFillPolicy": "null",
     "metric": "node.system.sys_in",
     "tags": { "aid": "*" }
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "null",
     "metric": "node.memory.used_mem",
     "tags": { "aid": "*" }
    }
   ]
  }
 ]
}