{
 "title": "Node Status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "aid", "label": "Node ID", "query": "select aid from agent" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h1 style='text-decoration:underline'>Current Status</h1>"
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "last",
     "downsampleAggregator": "last",
     "downsampleFillPolicy": "none",
     "metric": "node.memory.used_mem",
     "tags": { "aid": "${aid}" }
    }
   ]
  },
  {
   "title": "Load1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "last",
     "downsampleAggregator": "last",
     "downsampleFillPolicy": "none",
     "metric": "node.system.load1",
     "tags": { "aid": "${aid}" }
    }
   ]
  },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "last",
     "downsampleAggregator": "last",
     "downsampleFillPolicy": "none",
     "metric": "node.system.users",
     "tags": { "aid": "${aid}" }
    }
   ]
  },
  {
   "title": "Discovered Service",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "rawSql": "SELECT $__time(last_report_at), count(id) FROM service WHERE aid='${aid}' GROUP BY last_report_at\n"
    }
   ]
  },
  {
   "title": "Discovered Service",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "rawSql": "SELECT * from service where aid='$aid'"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "content": "<h1 style='text-decoration:underline'>System Health</h1>"
  },
  {
   "title": "Load 1/5/15($aid)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Load 1",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "metric": "node.system.load1",
     "tags": { "aid": "${aid}" }
    },
    {
     "aggregator": "max",
     "alias": "Load 5",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "metric": "node.system.load5",
     "tags": { "aid": "$aid" }
    },
    {
     "aggregator": "max",
     "alias": "Load 15",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "metric": "node.system.load15",
     "tags": { "aid": "$aid" }
    }
   ]
  },
  {
   "title": "System IN/CS($aid)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "Context Switch",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "sum",
     "downsampleFillPolicy": "none",
     "metric": "node.system.sys_cs",
     "tags": { "aid": "${aid}" }
    },
    {
     "aggregator": "sum",
     "alias": "Interrupt",
     "downsampleAggregator": "sum",
     "downsampleFillPolicy": "none",
     "metric": "node.system.sys_in",
     "tags": { "aid": "$aid" }
    }
   ]
  },
  {
   "title": "CPU($aid)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "System",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "metric": "node.cpu.sy",
     "tags": { "aid": "${aid}" }
    },
    {
     "aggregator": "max",
     "alias": "User",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "metric": "node.cpu.us",
     "tags": { "aid": "$aid" }
    },
    {
     "aggregator": "max",
     "alias": "Wait",
     "currentTagKey": "aid",
     "currentTagValue": "$aid",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "metric": "node.cpu.wa"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
   "content": "<h1 style='text-decoration:underline'>Memory & Disk</h1>"
  },
  {
   "title": "Swap($aid)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Total Swap",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "metric": "node.memory.total_swap",
     "tags": { "aid": "$aid" }
    },
    {
     "aggregator": "max",
     "alias": "Used Swap",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "metric": "node.memory.used_swap",
     "tags": { "aid": "${aid}" }
    }
   ]
  },
  {
   "title": "Memory($aid)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "alias": "Total Memory",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "metric": "node.memory.total_mem",
     "tags": { "aid": "$aid" }
    },
    {
     "aggregator": "max",
     "alias": "Used Memory",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "metric": "node.memory.used_mem",
     "tags": { "aid": "${aid}" }
    }
   ]
  },
  {
   "title": "Disk($aid)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "null",
     "downsampleInterval": "1h",
     "metric": "node.disk.used_util",
     "tags": { "aid": "${aid}", "mount_point": "*" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 },
   "content": "<h1 style='text-decoration:underline'>Network</h1>"
  },
  {
   "title": "Outbound Network ($aid)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "metric": "node.network.tx_bytes",
     "tags": { "aid": "${aid}", "interface": "*" }
    }
   ]
  },
  {
   "title": "Inbound Network ($aid)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "metric": "node.network.rx_bytes",
     "tags": { "aid": "${aid}", "interface": "*" }
    }
   ]
  }
 ]
}