{
 "title": "Service Status",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "aid", "label": "Node ID", "query": "select aid from agent" },
   {
    "name": "service_id",
    "label": "Service",
    "query": "select id from service where aid='$aid' order by last_report_at DESC"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Restart",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "rawSql": "SELECT $__time(collect_at), 1\nFROM service_history\nWHERE service_id='${service_id}' and $__timeFilter(collect_at)\n"
    }
   ]
  },
  {
   "title": "Service CPU Util",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "max",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "service.pidstat.cpu_util",
     "rawSql": "SELECT $__time(collect_at), 1\nFROM service_history\nWHERE service_id='${service_id}' and $__timeFilter(collect_at)\n",
     "tags": { "service_id": "${service_id}" }
    }
   ]
  },
  {
   "title": "Service Memory Util",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "max",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "service.pidstat.mem_util",
     "rawSql": "SELECT $__time(collect_at), 1\nFROM service_history\nWHERE service_id='${service_id}' and $__timeFilter(collect_at)\n",
     "tags": { "service_id": "${service_id}" }
    }
   ]
  },
  {
   "title": "Service Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "rawSql": "SELECT s.id, s.name service_name, a.aid, a.name node_name, s.type, s.last_report_at, s.status, s.pid from service s, agent a where s.aid=a.aid and s.id='$service_id'"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "null",
     "metric": "service.pidstat.cpu_util",
     "tags": { "service_id": "${service_id}" }
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "null",
     "metric": "service.pidstat.mem_util",
     "tags": { "service_id": "${service_id}" }
    }
   ]
  },
  {
   "title": "VSZ & RSS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "aggregator": "max",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "null",
     "metric": "service.pidstat.mem_vsz",
     "tags": { "service_id": "${service_id}" }
    },
    {
     "aggregator": "max",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "null",
     "metric": "service.pidstat.mem_rss",
     "tags": { "service_id": "${service_id}" }
    }
   ]
  }
 ]
}